local Eggtable = {
	CommonEgg = {
		Characters = {
			LiriliLarila = { Rarity = "Common", ImageID = "rbxassetid://134448919071311" },
			TimCheese = { Rarity = "Common", ImageID = "rbxassetid://108652630866520" },
			Fluriflura = { Rarity = "Common", ImageID = "rbxassetid://136901836107547" },
			TalpaDiFero = { Rarity = "Common", ImageID = "rbxassetid://123217525622291" },
			PipiKiwi = { Rarity = "Common", ImageID = "rbxassetid://111248857375054" },
			TrippiTroppi = { Rarity = "Uncommon", ImageID = "rbxassetid://120989940076448" },
		},
		Mutations = {
			Normal = { Rarity = "Common", ImageID = "rbxassetid://106756010556930" },
			Wet = { Rarity = "Common", ImageID = "rbxassetid://120238328117883" },
			Smelly = { Rarity = "Common", ImageID = "rbxassetid://85012053816457" },
			Windy = { Rarity = "Common", ImageID = "rbxassetid://92114363725514" },
			Cracked = { Rarity = "Uncommon", ImageID = "rbxassetid://109742681682706" },
		},
		Ultimates = {
			EnergyBeam = { Rarity = "Common", ImageID = "rbxassetid://103978675762588" },
			Fall = { Rarity = "Common", ImageID = "rbxassetid://130070087826055" },
			ToxicBreath = { Rarity = "Common", ImageID = "rbxassetid://81730221293843" },
			MeteorDrop = { Rarity = "Uncommon", ImageID = "rbxassetid://115635977476977" },
		},
	},
	UncommonEgg = {
		Characters = {
			LiriliLarila = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TimCheese = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fluriflura = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TalpaDiFero = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			PipiKiwi = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TrippiTroppi = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BanditoBobritto = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BonecaAmbalabu = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CactoHipopotamo = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
		},
		Mutations = {
			Normal = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Wet = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Smelly = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Windy = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Cracked = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Chilled = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
		},
		Ultimates = {
			EnergyBeam = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fall = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			ToxicBreath = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			MeteorDrop = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			FireBreath = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
		},
	},
	RareEgg = {
		Characters = {
			LiriliLarila = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TimCheese = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fluriflura = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TalpaDiFero = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			PipiKiwi = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TrippiTroppi = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BanditoBobritto = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BonecaAmbalabu = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CactoHipopotamo = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CappucinoAssassino = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BrrBrrPatapim = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BambiniCrostini = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BananitaDolphinita = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
		},
		Mutations = {
			Normal = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Wet = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Smelly = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Windy = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Cracked = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Chilled = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Rusty = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Glowing = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
		},
		Ultimates = {
			EnergyBeam = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fall = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			ToxicBreath = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			MeteorDrop = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			FireBreath = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			IceStorm = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
		},
	},
	EpicEgg = {
		Characters = {
			LiriliLarila = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TimCheese = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fluriflura = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TalpaDiFero = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			PipiKiwi = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			TrippiTroppi = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BanditoBobritto = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BonecaAmbalabu = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CactoHipopotamo = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CappucinoAssassino = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BrrBrrPatapim = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BambiniCrostini = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BananitaDolphinita = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			SalaminoPenguino = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			TrulimeroTrulicina = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			BlueberriniOctopusini = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			SigmaBoy = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
		},
		Mutations = {
			Normal = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Wet = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Smelly = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Windy = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Cracked = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Chilled = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Rusty = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Glowing = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Charged = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			Haunted = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
		},
		Ultimates = {
			EnergyBeam = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fall = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			ToxicBreath = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			MeteorDrop = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			FireBreath = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			IceStorm = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			AbyssalBlast = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
		},
	},
	LegendaryEgg = {
		Characters = {
			TrippiTroppi = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BanditoBobritto = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			BonecaAmbalabu = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CactoHipopotamo = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			CappucinoAssassino = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BrrBrrPatapim = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BambiniCrostini = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BananitaDolphinita = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			SalaminoPenguino = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			TrulimeroTrulicina = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			BlueberriniOctopusini = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			SigmaBoy = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			ChimpanziniBananini = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			BallerinaCappucina = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			LionelCactuseli = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			GlorboFruttodrillo = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
		},
		Mutations = {
			Normal = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Wet = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Smelly = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Windy = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Cracked = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Chilled = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Rusty = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Glowing = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Charged = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			Haunted = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
		},
		Ultimates = {
			EnergyBeam = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fall = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			ToxicBreath = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			MeteorDrop = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			FireBreath = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			IceStorm = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			AbyssalBlast = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			OblivionStrike = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
		},
	},
	MythicEgg = {
		Characters = {
			CappucinoAssassino = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BrrBrrPatapim = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BambiniCrostini = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			BananitaDolphinita = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			SalaminoPenguino = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			TrulimeroTrulicina = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			BlueberriniOctopusini = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			SigmaBoy = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			ChimpanziniBananini = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			BallerinaCappucina = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			LionelCactuseli = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			GlorboFruttodrillo = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			SpioniroGolubiro = { Rarity = "Mythic", ImageID = "rbxassetid://0000" },
			BombombiniGusini = { Rarity = "Mythic", ImageID = "rbxassetid://0000" },
			GorilloWatermelondrillo = { Rarity = "Mythic", ImageID = "rbxassetid://0000" },
			OrangutiniAnanassini = { Rarity = "Mythic", ImageID = "rbxassetid://0000" },
		},
		Mutations = {
			Normal = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Wet = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Smelly = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Windy = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Cracked = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Chilled = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			Rusty = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Glowing = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			Charged = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			Haunted = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
		},
		Ultimates = {
			EnergyBeam = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			Fall = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			ToxicBreath = { Rarity = "Common", ImageID = "rbxassetid://0000" },
			MeteorDrop = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			FireBreath = { Rarity = "Uncommon", ImageID = "rbxassetid://0000" },
			IceStorm = { Rarity = "Rare", ImageID = "rbxassetid://0000" },
			AbyssalBlast = { Rarity = "Epic", ImageID = "rbxassetid://0000" },
			OblivionStrike = { Rarity = "Legendary", ImageID = "rbxassetid://0000" },
			InfinityNova = { Rarity = "Mythic", ImageID = "rbxassetid://0000" },
		},
	},
}

return Eggtable
