return {
	[1] = {
		Name = "Cherry Case",
		IconId = "rbxassetid://100431950815620",
		Price = "R$128",
		Drops = { -- SkinIds
			3,
			4,
			9,
			10,
			17,
			19,
			20,
			21,
			22,
			
			
			14,
			15,
			24,
			
			26,
			
			27,
			28,
			30,
			32
			
		}
	},
	[2] = {
		Name = "Vip Case",
		IconId = "rbxassetid://140102620397332",
		Price = "R$256",
		Drops = { -- SkinIds
			1,
			2,
			6,
			7,
			8,
			22,
			18,
			16,
			11,
			5,
			
			34,
			
			12,
			13,
			23,
			25,
			29,
			31,
			33,
			35
		}
	},

}