return {
	Currency = {
		Coins = 0,
		RebirthTokens = 0,
		RebirthCount = 0,
	},

	Pinata = {
		Current = 'Pocket Pinata',
		XP = 0,
		Level = 1,
		Health = 100,
	},

	Inventory = {
		EquippedWeapon = 'RustyKnife',
		Weapons = { 'RustyKnife' },
		Items = {},
		Candies = {},
		Pinatas = { 'Pocket Pinata' },
	},

	Plot = {
		Droppers = {},
	},

	Settings = {},
	Gamepasses = {},

	Metadata = {
		LastLogin = 0,
		TotalPlayTime = 0,
	},
}
