return {
	Currency = {
		Coins = 0,
		RebirthTokens = 0,
		RebirthCount = 0,
	},

	Pinata = {
		Current = 'Pocket Pinata',
		XP = 0,
		Level = 1,
		Health = 100,
	},

	Inventory = {
		EquippedWeapon = 'RustyKnife',
		Weapons = { 'RustyKnife' },
		Items = {},
		Candies = {},
		Pinatas = { 'Pocket Pinata' },
	},

	Plot = {
		Machines = {},
		MachineOwnership = {},
	},

	Boost = {
		Lucky2X = false,
		Coins2X = false,
		Candy2XForever = false
	},
	BoostTimes = {},
	Settings = {},
	Gamepasses = {
		BigCandysOffline = false,
		SlotCandy = false,
		Candy2XForever = false,
		StarterPack = false,
	},

	Metadata = {
		LastLogin = 0,
		TotalPlayTime = 0,
	},
}
