return {
	["Plastic"] = { ID = 1, PLPS = 1.0 },
	["SmoothPlastic"] = { ID = 2, PLPS = 1.0 },
	["Neon"] = { ID = 3, PLPS = 0.25 },

	["Wood"] = { ID = 4, PLPS = 0.6 },
	["WoodPlanks"] = { ID = 5, PLPS = 0.6 },

	["Concrete"] = { ID = 6, PLPS = 1.3 },
	["Brick"] = { ID = 7, PLPS = 1.5 },
	["Cobblestone"] = { ID = 8, PLPS = 1.6 },
	["Rock"] = { ID = 9, PLPS = 1.6 },
	["Basalt"] = { ID = 10, PLPS = 1.8 },
	["Asphalt"] = { ID = 11, PLPS = 1.4 },
	["Granite"] = { ID = 12, PLPS = 1.8 },
	["Marble"] = { ID = 13, PLPS = 1.6 },
	["Slate"] = { ID = 14, PLPS = 1.6 },
	["Pebble"] = { ID = 15, PLPS = 1.4 },

	["Sand"] = { ID = 16, PLPS = 0.4 },
	["Grass"] = { ID = 17, PLPS = 0.5 },
	["LeafyGrass"] = { ID = 18, PLPS = 0.5 },
	["Ground"] = { ID = 19, PLPS = 0.6 },
	["Mud"] = { ID = 20, PLPS = 0.5 },
	["Snow"] = { ID = 21, PLPS = 0.25 },
	["Ice"] = { ID = 22, PLPS = 0.15 },
	["Salt"] = { ID = 23, PLPS = 0.4 },
	["Glacier"] = { ID = 24, PLPS = 0.3 },
	["CrackedLava"] = { ID = 25, PLPS = 2.0 },

	["Metal"] = { ID = 26, PLPS = 3.0 },
	["CorrodedMetal"] = { ID = 27, PLPS = 2.6 },
	["DiamondPlate"] = { ID = 28, PLPS = 3.5 },
	["Foil"] = { ID = 29, PLPS = 2.2 },

	["Glass"] = { ID = 30, PLPS = 0.15 },

	["Fabric"] = { ID = 31, PLPS = 0.25 },
	["Carpet"] = { ID = 32, PLPS = 0.25 },
	["Leather"] = { ID = 33, PLPS = 0.4 },
	["Rubber"] = { ID = 34, PLPS = 0.6 },

	["CeramicTiles"] = { ID = 35, PLPS = 1.5 },
	["Pavement"] = { ID = 36, PLPS = 1.5 },
	["RoofShingles"] = { ID = 37, PLPS = 1.0 },
	["Plaster"] = { ID = 38, PLPS = 0.8 },
	["Cardboard"] = { ID = 39, PLPS = 0.5 },
	["Paper"] = { ID = 40, PLPS = 0.25 },
}
