
-- [[ NotInDailyStore = true -- faz a skin nn aparecer na loja diaria]]

return {

	[1] = {
		Name = "AK47 Ice Cold",
		Weapon = "AK47",
		Icon = "rbxassetid://72428515645312",
		Rarity = "Bad",
		Price = 2500,
	},
	[2] = {
		Name = "AK47 Red Hot",
		Weapon = "AK47",
		Icon = "rbxassetid://118495836118289",
		Rarity = "Ok",
		Price = 5000,
	},
	[3] = {
		Name = "AK47 M1DN1GHT",
		Weapon = "AK47",
		Icon = "rbxassetid://117395345686416",
		Rarity = "Goated",
		Price = 10000,
	},

	[4] = {
		Name = "AWP Touch Grass",
		Weapon = "AWP",
		Icon = "rbxassetid://115157975305958",
		Rarity = "Bad",
		Price = 2000,
	},
	[5] = {
		Name = "AWP Asuka",
		Weapon = "AWP",
		Icon = "rbxassetid://95200982137851",
		Rarity = "Goated",
		Price = 8000,
	},
	[6] = {
		Name = "AWP White Monster",
		Weapon = "AWP",
		Icon = "rbxassetid://121834574486199",
		Rarity = "Goated",
		Price = 10000,
	},

	[7] = {
		Name = "Deagle V.I.P",
		Weapon = "Deagle",
		Icon = "rbxassetid://120085182633376",
		Rarity = "Goated",
		Price = 10000,
	},

	[8] = {
		Name = "Dual Berettas Old Money",
		Weapon = "Dual Berettas",
		Icon = "rbxassetid://126621462332277",
		Rarity = "Bad",
		Price = 2000,
	},
	[9] = {
		Name = "Dual Berettas Morale",
		Weapon = "Dual Berettas",
		Icon = "rbxassetid://126621462332277",
		Rarity = "Ok",
		Price = 4000,
	},
	[10] = {
		Name = "Dual Berettas Evangelion",
		Weapon = "Dual Berettas",
		Icon = "rbxassetid://118716610648812",
		Rarity = "Goated",
		Price = 9000,
	},

	[11] = {
		Name = "Dual Uzi Sneakers",
		Weapon = "Dual Uzi",
		Icon = "rbxassetid://82722950065201",
		Rarity = "Goated",
		Price = 15000,
	},

	[12] = {
		Name = "Hunter Knife Sci-fi",
		Weapon = "Hunter Knife",
		Icon = "rbxassetid://96941533930864",
		Rarity = "Holy",
		Price = 40000,
		NotInDailyStore = true,
	},
	[13] = {
		Name = "Hunter Knife Molten Fangs",
		Weapon = "Hunter Knife",
		Icon = "rbxassetid://79487553756029",
		Rarity = "Holy",
		Price = 45000,
		NotInDailyStore = true,
	},

	[14] = {
		Name = "Knife Sci-fi",
		Weapon = "Knife",
		Icon = "rbxassetid://136175803098158",
		Rarity = "Holy",
		Price = 30000,
		NotInDailyStore = true,
	},
	[15] = {
		Name = "Knife Kage no Kiba",
		Weapon = "Knife",
		Icon = "rbxassetid://85938596411637",
		Rarity = "Holy",
		Price = 36000,
		NotInDailyStore = true,
	},
	
	[16] = {
		Name = "Makarov Battery AAA",
		Weapon = "Makarov",
		Icon = "rbxassetid://104043412938172",
		Rarity = "Bad",
		Price = 2000,
	},
	[17] = {
		Name = "Makarov Oyasumi Punpun",
		Weapon = "Makarov",
		Icon = "rbxassetid://81320742970282",
		Rarity = "Ok",
		Price = 6000,
	},
	
	[18] = {
		Name = "Remington870 Freedom",
		Weapon = "Remington870",
		Icon = "rbxassetid://113148350537399",
		Rarity = "Bad",
		Price = 2000,
	},
	[19] = {
		Name = "Remington870 Rei Ayanami",
		Weapon = "Remington870",
		Icon = "rbxassetid://138135198986080",
		Rarity = "Goated",
		Price = 16000,
	},
	
	[20] = {
		Name = "SVD Red Carbon",
		Weapon = "SVD",
		Icon = "rbxassetid://93168252008244",
		Rarity = "Bad",
		Price = 2000,
	},
	[21] = {
		Name = "SVD Raze",
		Weapon = "SVD",
		Icon = "rbxassetid://93486016652682",
		Rarity = "Ok",
		Price = 7000,
	},
	
	[22] = {
		Name = "USP Jackpot",
		Weapon = "USP",
		Icon = "rbxassetid://120354058254585",
		Rarity = "Bad",
		Price = 1500,
	},
	
	[23] = {
		Name = "Cattle Prod Golden Tech",
		Weapon = "Cattle Prod",
		Icon = "rbxassetid://139347059855612",
		Rarity = "Holy",
		Price = 53500,
		NotInDailyStore = true,
	},
	[24] = {
		Name = "Machete Blue Pearl",
		Weapon = "Machete",
		Icon = "rbxassetid://120354058254585",
		Rarity = "Holy",
		Price = 48000,
		NotInDailyStore = true,
	},
	[25] = {
		Name = "Machete Desert Prince",
		Weapon = "Machete",
		Icon = "rbxassetid://120354058254585",
		Rarity = "Holy",
		Price = 50000,
		NotInDailyStore = true,
	},

	[26] = {
		Name = "Gloves Bloodgrip",
		Price = 70000,
		Weapon = "Gloves",
		Rarity = "Holy",
		Icon = "rbxassetid://102561572257580",
		NotInDailyStore = true,
	},
	[27] = {
		Name = "Cattle Prod Comic Book",
		Weapon = "Cattle Prod",
		Icon = "rbxassetid://78066828487326",
		Rarity = "Holy",
		Price = 53500,
		NotInDailyStore = true,
	},
	[28] = {
		Name = "Katana Oni",
		Weapon = "Katana",
		Icon = "rbxassetid://111867486073672",
		Rarity = "Holy",
		Price = 66000,
		NotInDailyStore = true,
	},
	[29] = {
		Name = "Katana Purple Blade",
		Weapon = "Katana",
		Icon = "rbxassetid://100103980691140",
		Rarity = "Holy",
		Price = 72000,
		NotInDailyStore = true,
	},
	[30] = {
		Name = "Karambit Speedster",
		Weapon = "Karambit",
		Icon = "rbxassetid://115345220606238",
		Rarity = "Holy",
		Price = 84000,
		NotInDailyStore = true,
	},
	[31] = {
		Name = "Karambit Apex Fang",
		Weapon = "Karambit",
		Icon = "rbxassetid://139966980761656",
		Rarity = "Holy",
		Price = 90000,
		NotInDailyStore = true,
	},
	[32] = {
		Name = "Butterfly Crimson Facet",
		Weapon = "Butterfly",
		Icon = "rbxassetid://79335192289091",
		Rarity = "Holy",
		Price = 111111,
		NotInDailyStore = true,
	},
	[33] = {
		Name = "Butterfly Rampage Reactor",
		Weapon = "Butterfly",
		Icon = "rbxassetid://97463066370320",
		Rarity = "Holy",
		Price = 141414,
		NotInDailyStore = true,
	},
	[34] = {
		Name = "Gloves Eclipse Velvet",
		Price = 70000,
		Weapon = "Gloves",
		Rarity = "Holy",
		Icon = "rbxassetid://130423123318258",
		NotInDailyStore = true,
	},
	[35] = {
		Name = "Gloves Cryo Hex",
		Price = 70000,
		Weapon = "Gloves",
		Rarity = "Holy",
		Icon = "rbxassetid://72913498943980",
		NotInDailyStore = true,
	},
	[36] = {
		Name = "AWP V.I.P",
		Weapon = "AWP",
		Icon = "rbxassetid://128289932715468",
		Rarity = "Holy",
		Price = 50000,
	},

}



