local BOOST_DATA = {
	Lucky2X = {
		Name = "Lucky2X",
		Image = "rbxassetid://88288642677615",
		Duration = 120,
		Title = "Lucky x2"
	},
	Coins2X = {
		Name = "Coins2X",
		Image = "rbxassetid://104541795919035",
		Duration = 120,
		Title = "Coins x2"
	},
	MoreCandy = {
		Name = "More Candy",
		Image = "rbxassetid://113378607541281",
		Duration = 120,
		Title = "More Candy"
	},
	Candy2XForever = {
		Name = "Candy2XForever",
		Image = "rbxassetid://113378607541281",
		Duration = math.huge,
		Title = "Candy x2 Forever",
		IsPermanent = true,
		GamepassId = 1711483593
	},
}

return BOOST_DATA