return {
	
	{
		MapName = "cs_Office",
		DisplayName = "cs_Office",
		ImageId = "rbxassetid://127587350449200",
	},
	{
		MapName = "Crossroads",
		DisplayName = "Crossroads",
		ImageId = "rbxassetid://119322937557101",
	},
	{
		MapName = "NewStatePlaza",
		DisplayName = "NewState Plaza",
		ImageId = "rbxassetid://73115030284851",
	},
	{
		MapName = "CityTemplate",
		DisplayName = "City Template",
		ImageId = "rbxassetid://5325694343",
	},
}