local Weapons = {
	[1] = {
		Name = "USP",
		Price = 0,
		Slot = "Secondary",
		Icon = "rbxassetid://132112642171377",
		IconHud = "rbxassetid://127142430184432",
	},
	
	[2] = {
		Name = "AK47",
		Price = 0,
		Slot = "Primary",
		Icon = "rbxassetid://81853918864557",
		IconHud = "rbxassetid://75714051275493",
	},
	
	[3] = {
		Name = "Knife",
		Price = 0,
		Slot = "Melee",
		Icon = "rbxassetid://124780541238427",
		IconHud = "rbxassetid://118355303205963",
	},
	
	[4] = {
		Name = "Remington870",
		Price = 10000,
		Slot = "Primary",
		Icon = "rbxassetid://106461176067605",
		IconHud = "rbxassetid://74917570684092",
	},
	
	[5] = {
		Name = "AWP",
		Price = 24000,
		Slot = "Primary",
		Icon = "rbxassetid://136569630684783",
		IconHud = "rbxassetid://92256226901763",
	},
	
	[6] = {
		Name = "Katana",
		Price = 20000,
		Slot = "Melee",
		Icon = "rbxassetid://92116357307754",
		IconHud = "rbxassetid://118464411148871",
	},
	
	[7] = {
		Name = "Gloves",
		Price = 0,
		Slot = "Gloves",
		Icon = "rbxassetid://96881763891925",
		IconHud = "rbxassetid://108702759537150",
	},
	

	
	[8] = {
		Name = "Deagle",
		Price = 18000,
		Slot = "Secondary",
		Icon = "rbxassetid://108863891802890",
		IconHud = "rbxassetid://134603143652117",
	},
	[9] = {
		Name = "Makarov",
		Price = 100,
		Slot = "Secondary",
		Icon = "rbxassetid://96707818870905",
		IconHud = "rbxassetid://94619594108409",
	},
	[10] = {
		Name = "SVD",
		Price = 15500,
		Slot = "Primary",
		Icon = "rbxassetid://110437128670624", 
		IconHud = "rbxassetid://87456982064382",
	},
	[11] = {
		Name = "Dual Uzi",
		Price = 29000,
		Slot = "Primary",
		Icon = "rbxassetid://85028123896487", 
		IconHud = "rbxassetid://92353577262762",
	},
	[12] = {
		Name = "Dual Berettas",
		Price = 14000,
		Slot = "Secondary",
		Icon = "rbxassetid://119806755751540",
		IconHud = "rbxassetid://98543131021049",
	},
	[13] = {
		Name = "Hunter Knife",
		Price = 500,
		Slot = "Melee",
		Icon = "rbxassetid://115487678818036",
		IconHud = "rbxassetid://116400239088407",
	},
	[14] = {
		Name = "Machete",
		Price = 5000,
		Slot = "Melee",
		Icon = "rbxassetid://103809872268599",
		IconHud = "rbxassetid://131610737550631",
	},
	[15] = {
		Name = "Cattle Prod",
		Price = 10000,
		Slot = "Melee",
		Icon = "rbxassetid://125689151272139",
		IconHud = "rbxassetid://75532048161732",
	},
	[16] = {
		Name = "Karambit",
		Price = 24000,
		Slot = "Melee",
		Icon = "rbxassetid://72558198657954",
		IconHud = "rbxassetid://137277061774405",
	},
	[17] = {
		Name = "Butterfly",
		Price = 28000,
		Slot = "Melee",
		Icon = "rbxassetid://74460308285034",
		IconHud = "rbxassetid://100262165875812",
	},


	
}

return Weapons